//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekzamen.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Zhanr { get; set; }
        public string Avtor { get; set; }
        public decimal Cost { get; set; }
        public int Kolvo_shop { get; set; }
        public int Kolvo_sklad { get; set; }
        public string Description { get; set; }
        public string Imagess { get; set; }
    }
}
